"use client";
import { FormEvent, useState } from "react"; import { Bot, CalendarCheck, Send, ShieldCheck, Sparkles } from "lucide-react"; import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle,SheetTrigger } from "@/components/ui/sheet";
type Message={from:"bot"|"user",text:string};
const facts=[
  {keys:["included","amenities","come with","provide"],answer:"Booth renters have access to the TV, wash bowl, one chair dryer, broom, dustpan, and regular trash cans. The larger suite includes a table, its own large trash can, a broom and dustpan. Towels and rags are available in the open for use."},
  {keys:["wash","bowl","sink"],answer:"Yes—there is a wash bowl available."},
  {keys:["dryer","chair dryer"],answer:"Yes—K Aura has one chair dryer available."},
  {keys:["table","esthetician"],answer:"The larger suite includes a table, its own large trash can, a broom and dustpan. Towels and rags are available in the open for use."},
  {keys:["tools","products","scissors","blow dryer","flat iron","curling","bleach","color","ring light","tripod","cape"],answer:"Products and professional tools are not included. Please bring everything needed for your services—including scissors, a handheld blow dryer, flat or curling irons, bleach or color, ring lights, tripods, hair capes, and any mobile or rolling esthetician table."},
  {keys:["tv","television"],answer:"Yes—renters may use the TV during their reservation."},
  {keys:["trash","broom","clean","towel","rag"],answer:"The larger suite has its own large trash can, broom and dustpan. Towels and rags are available in the open for use. Please return the space ready for the next professional."},
  {keys:["code","access","door","enter"],answer:"Approved renters receive the salon access code with their confirmed reservation details. For safety, the code is never shared in public chat."},
  {keys:["tour","visit","see salon","look around"],answer:"Tours are reserved for professionals seriously considering a chair or suite rental. Tap “Request a tour” below and Bre’s team will confirm the appointment."},
  {keys:["chair","cosmetologist","hair"],answer:"Chair rentals are designed for cosmetologists and hair professionals. You can reserve a 12-hour rental or request a serious tour inquiry."},
  {keys:["suite","facial","esthetic"],answer:"The larger suite includes a table, its own large trash can, a broom and dustpan. Towels and rags are available in the open for use. Products, tools and ring lights are not supplied."},
];
function answerFor(input:string){const q=input.toLowerCase();const hit=facts.find(f=>f.keys.some(k=>q.includes(k)));return hit?.answer||"I can help with tours, chair or suite rentals, included amenities, what to bring, and salon access. For anything else, Bre’s team can follow up through a tour request."}
export default function Concierge(){const [messages,setMessages]=useState<Message[]>([{from:"bot",text:"Hi! I’m the K Aura Concierge. Ask me what’s included, what to bring, or how to request a serious salon tour."}]);const [input,setInput]=useState("");const [tour,setTour]=useState(false);const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);
function ask(e:FormEvent){e.preventDefault();if(!input.trim())return;const q=input.trim();setMessages(m=>[...m,{from:"user",text:q},{from:"bot",text:answerFor(q)}]);setInput("")}
async function submitTour(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/tours",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});setBusy(false);if(r.ok)setSent(true);else alert((await r.json()).error)}
return <Sheet><SheetTrigger className="chat-trigger" aria-label="Open K Aura Concierge"><Sparkles size={20}/><span>Ask K Aura</span></SheetTrigger><SheetContent className="concierge-panel"><SheetHeader className="concierge-head"><div className="bot-mark"><Bot/></div><SheetTitle>K Aura Concierge</SheetTitle><SheetDescription>Rental answers and serious tour inquiries</SheetDescription></SheetHeader><div className="chat-messages">{messages.map((m,i)=><div className={`chat-message ${m.from}`} key={i}>{m.text}</div>)}</div><div className="quick-questions"><button onClick={()=>setMessages(m=>[...m,{from:"user",text:"What’s included?"},{from:"bot",text:facts[0].answer}])}>What’s included?</button><button onClick={()=>setMessages(m=>[...m,{from:"user",text:"What should I bring?"},{from:"bot",text:facts[4].answer}])}>What should I bring?</button><button onClick={()=>setTour(true)}>Request a tour</button></div>{tour&&!sent&&<form className="tour-form" onSubmit={submitTour}><h3><CalendarCheck size={18}/> Serious tour inquiry</h3><p>Tell Bre’s team when you would like to tour. This sends a request to K Aura; your time is confirmed only after the team follows up.</p><input required name="fullName" placeholder="Full name"/><input required type="email" name="email" placeholder="Email"/><input required type="tel" name="phone" placeholder="Phone"/><select required name="rentalType" defaultValue=""><option value="" disabled>Interested in…</option><option value="chair">Booth rental</option><option value="suite">Larger suite</option></select><div><input required type="date" name="preferredDate"/><input required type="time" name="preferredTime"/></div><textarea name="message" placeholder="Anything Bre should know?"/><button disabled={busy}>{busy?"Sending…":"Send tour request"}<Send size={15}/></button></form>}{sent&&<div className="tour-success"><ShieldCheck/><strong>Tour request received.</strong><span>Bre’s team will contact you to confirm. This is not a Calendly appointment yet.</span></div>}<form className="chat-input" onSubmit={ask}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask a question…" aria-label="Ask K Aura a question"/><button aria-label="Send question"><Send size={18}/></button></form></SheetContent></Sheet>}
